name: test-build-push

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [ main ]

# jobs:
#   test:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read
#       packages: write
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2
#       - name: Test build
#         run: |
#             docker-compose up -d;
#             sleep 10;
#             CODE=$(curl -w '%{http_code}' \
#                   -SL \
#                   -o /dev/null \
#                   -X GET \
#                   localhost:8080/health)
#             if [[ $CODE != 200 ]]; then exit 1; fi;
#             docker-compose down;
  
  build:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log into registry
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Set env variable
        id: set-env
        run: echo "IMAGE_TAG=$(date +'%Y%m%d.%H%M%S')" >> $GITHUB_ENV

      - name: output variable
        run: echo "${{ env.IMAGE_TAG }}"

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: ${{ github.event_name = 'push' }}
          tags: ${{ secrets.DOCKER_REGISTRY }}/gitops-app:latest, ${{ secrets.DOCKER_REGISTRY }}/gitops-app:${{ env.IMAGE_TAG }}

      - name: output variable
        run: echo "${{ env.IMAGE_TAG }}"

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: output variable
        run: echo "${{ env.IMAGE_TAG }}"
  #     - name: Open PR in Environment Repository for new App Version
  #       env:
  #         ENV_REPO: ${{ github.event.repository.owner.name }}/gitops-env
  #       uses: benc-uk/workflow-dispatch@v1.1
  #       with:
  #         workflow: New Application Version
  #         token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  #         inputs: '{"tag_name": "${{ env.IMAGE_TAG }}", "app_repo": "${{ github.event.repository.name }}", "image": "${{ secrets.DOCKER_REGISTRY }}/${{ github.event.repository.name }}:${{ env.TAG_NAME }}"}'
  #         ref: refs/heads/main